app/src/AppBundle/Entity/Address.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AddressRepository")
 * @ORM\Table(name="address")
 */
class Address
{
    public const TYPE_LOADING_POINT   = 1;
    public const TYPE_CROSSING        = 2;
    public const TYPE_UNLOADING_POINT = 3;

    public const ALL_TYPES = [
        self::TYPE_LOADING_POINT   => 'Место погрузки',
        self::TYPE_CROSSING        => 'Пересечение',
        self::TYPE_UNLOADING_POINT => 'Место разгрузки',
    ];

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @return int
     */
    public function getType(): int
    {
        return $this->type;
    }

    /**
     * @param int $type
     *
     * @return Address
     */
    public function setType(int $type): Address
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return Address
     */
    public function setName(string $name): Address
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNamedType(): string
    {
        return self::ALL_TYPES[$this->type] ?? 'Address have not type';
    }

    /**
     * @return bool
     */
    public function isLoading(): bool
    {
        return $this->type === self::TYPE_LOADING_POINT;
    }

    /**
     * @return bool
     */
    public function isUnload(): bool
    {
        return $this->type === self::TYPE_UNLOADING_POINT;
    }

    /**
     * @return bool
     */
    public function isCrossing(): bool
    {
        return $this->type === self::TYPE_CROSSING;
    }

    /**
     * @return string
     */
    public function getCustomFieldForCargoContract(): string
    {
        return CargoContract::TYPES_FOR_FIELDS[$this->type];
    }
}

app/src/AppBundle/Controller/AddressController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Address;
use AppBundle\Entity\CargoContract;
use AppBundle\Repository\AddressRepository;
use AppBundle\Response\Json\ErrorJsonResponse;
use AppBundle\Response\Json\SuccessJsonResponse;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/address", name="app_address_")
 */
class AddressController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     *
     * @param AddressRepository $addressRepository
     *
     * @return Response
     */
    public function main(AddressRepository $addressRepository): Response
    {
        return $this->render('@App/Address/main.html.twig', [
            'addresses' => $addressRepository->findAll(),
            'types' => CargoContract::TYPES_FOR_FIELDS,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete")
     *
     * @param Address                $address
     * @param EntityManagerInterface $entityManager
     *
     * @return JsonResponse
     */
    public function delete(Address $address, EntityManagerInterface $entityManager): JsonResponse
    {
        try {
            $entityManager->remove($address);
            $entityManager->flush();

            return new SuccessJsonResponse();
        } catch (\Throwable $exception) {
            return new ErrorJsonResponse($exception);
        }
    }

    /**
     * @Route("/create", name="create")
     *
     * @param Request                $request
     * @param EntityManagerInterface $entityManager
     *
     * @return JsonResponse
     */
    public function create(Request $request, EntityManagerInterface $entityManager): JsonResponse
    {
        try {
            $name = $request->get('name');
            $type = $request->get('type');

            if (null === $name) {
                return new ErrorJsonResponse('Введите имя');
            }

            if (null === $type) {
                return new ErrorJsonResponse('Введите тип');
            }

            if (!Address::ALL_TYPES[(int) $type]) {
                return new ErrorJsonResponse('Не верный тип');
            }

            $address = new Address();
            $address
                ->setName($name)
                ->setType((int) $type);

            $entityManager->persist($address);
            $entityManager->flush();

            return new SuccessJsonResponse($address->getNamedType() . ' ' . $address->getName() . ' создано');
        } catch (\Throwable $exception) {
            return new ErrorJsonResponse($exception);
        }

    }
}

app/src/AppBundle/Resources/views/Address/main.html.twig
{% extends '@App/Default/base.html.twig' %}

{% set russianNamesForAddress = constant('AppBundle\\Entity\\CargoContract::TRANSLATE_FOR_ADRESS') %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <form class="js-create-address" action="{{ path('app_address_create') }}">
                    <div class="form-group row">
                        <label for="${value}" class="col-sm-1 col-form-label">Имя</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-5">
                            <label for="${value}" class="col-sm-5 col-form-label">Тип</label>
                            <select class="form-control " name="type">
                            {% for value, type in types %}
                                <option value="{{ value }}">{{ russianNamesForAddress[type] }}</option>
                            {% endfor %}
                            </select>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Создать">
                </form>
            </div>
            <div class="col-md-7">
                <table class="table">
                    <thead>
                    <th>Название</th>
                    <th>Тип</th>
                    </thead>
                    <tbody>
                    {% for address in addresses %}
                        <tr>
                            <td>{{ address.name }}</td>
                            <td>{{ address.namedType }}</td>
                            <td>
                                <button class="js-btn-delete btn btn-primary"
                                        data-url-to-delete="{{ path('app_address_delete', {'id': address.id}) }}">
                                    Удалить
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(() => {
            const $btns = $('.js-btn-delete');
            const $form = $('.js-create-address');
            const $select = $('select[name=type]');

            $form.on('submit', (event) => {
               event.preventDefault();
               event.stopPropagation();

               const url = $form.attr('action');
               const name = $form.find('input[name=name]').val();
               const type =  $select.children("option:selected").val();

               $.ajax({
                   data: {
                       name: name,
                       type: type
                   },
                   url: url,
                   success: (res) => {
                       if (res.status === 'success') {
                           alert(res.message);
                           window.location.reload();
                       } else {
                           alert(res.message);
                       }
                   }
               })
            });

            $btns.on('click', (event) => {
                const $btn = $(event.currentTarget);
                const url = $btn.data('url-to-delete');
                const $tr = $btn.parent().parent();

                $.ajax({
                    beforeSend: () => {
                        $btn.attr('disabled', true);
                    },
                    url: url,
                    success: (res) => {
                        if (res.status === 'success') {
                            $tr.remove();
                        } else {
                            alert(res.message);
                            $btn.attr('disabled', false);
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}