app/src/AppBundle/Entity/Contract.php
<?php

namespace AppBundle\Entity;

class Contract implements FileEntityInterface
{
    public const CLASSES = [
        Document::CARGO_CONTRACT      => CargoContract::class,
        Document::PHYSICAL_PERSON_AGR => PhysicalPersonsLeaseAgreement::class,
        Document::LEGAL_PERSON_AGR    => LegalEntitiesLeaseAgreement::class,
    ];

    /**
     * @var int
     */
    protected $id;

    /**
     * @var string
     */
    protected $fileName;

    /**
     * @var \DateTime
     */
    protected $dateCreated;

    /**
     * @var string
     */
    protected $title;

    public function __construct()
    {
        $this->dateCreated = new \DateTime();
    }

    /**
     * @return null|string
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string $fileName
     *
     * @return static
     */
    public function setFileName(string $fileName): FileEntityInterface
    {
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    /**
     * @param \DateTime $dateCreated
     */
    public function setDateCreated(\DateTime $dateCreated): void
    {
        $this->dateCreated = $dateCreated;
    }

    /**
     * @return null|string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     *
     * @return Contract
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

app/src/AppBundle/Entity/Document.php
<?php

namespace AppBundle\Entity;

use AppBundle\Component\FileSettings;
use AppBundle\Component\Helper\UpdateMergeFieldHelper;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\DocumentRepository")
 * @ORM\Table(name="documents")
 */
class Document implements FileEntityInterface
{
    public const PHYSICAL_PERSON_AGR = 'PhysicalPersonsLeaseAgreement';
    public const LEGAL_PERSON_AGR    = 'LegalEntitiesLeaseAgreement';
    public const CARGO_CONTRACT      = 'CargoContract';

    public const RUSSIAN_TITLES = [
        self::PHYSICAL_PERSON_AGR => 'Договор аренды ФЗ',
        self::LEGAL_PERSON_AGR    => 'Договор аренды ЮР',
        self::CARGO_CONTRACT      => 'Договор Грузоперевозки',
    ];

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $fileName;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    private $columns;

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     *
     * @return Document
     */
    public function setTitle(string $title): Document
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string $fileName
     *
     * @return self
     */
    public function setFileName(string $fileName): FileEntityInterface
    {
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * @return array
     */
    public function getColumns(): ?array
    {
        return $this->columns;
    }

    /**
     * @param array $columns
     *
     * @return Document
     */
    public function setColumns(array $columns): Document
    {
        $this->columns = $columns;

        return $this;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getFilePath(): string
    {
        return FileSettings::DOC_FOLDER . DIRECTORY_SEPARATOR . $this->fileName;
    }

    /**
     * @return string
     */
    public function transformArrayToString(): string
    {
        return implode(', ', $this->columns ?? []);
    }

    /**
     * @throws \Exception
     *
     * @return array
     */
    public function getMergeFieldsWithoutNotUsedFields(): array
    {
        switch ($this->title) {
            case self::PHYSICAL_PERSON_AGR:
                return $this->getCombineArrayForTranslate(PhysicalPersonsLeaseAgreement::TRANSLATION_FIELDS);
            case self::LEGAL_PERSON_AGR:
                return $this->getCombineArrayForTranslate(LegalEntitiesLeaseAgreement::TRANSLATION_FIELDS);
            case self::CARGO_CONTRACT:
                return $this->getCombineArrayForTranslate(CargoContract::TRANSLATION_FIELDS);
            default:
                throw new \Exception('No translate');
        }
    }

    /**
     * @param array $translate
     *
     * @return array
     */
    private function getCombineArrayForTranslate(array $translate): array
    {
        $arr = array_combine($translate, array_unique(array_diff($this->columns, UpdateMergeFieldHelper::NOT_INPUT_VALUES[$this->title])));

        switch ($this->title) {
            case Document::PHYSICAL_PERSON_AGR:
                $arr = array_merge($arr, ['Роспись' => 'image' . STAMP::PAINTING_ID_PHY]);
            break;
            case Document::LEGAL_PERSON_AGR:
                $arr = array_merge($arr, ['Роспись' => 'image' . STAMP::PAINTING_ID, 'Штамп' => 'image' . STAMP::STAMP_ID]);
            break;

        }

        return $arr;
    }

    /**
     * @return string
     */
    public function getRussinTitle(): string
    {
        return self::RUSSIAN_TITLES[$this->title] ?? 'Not translate';
    }

    /**
     * @return bool
     */
    public function isCargo(): bool
    {
        return $this->title === self::CARGO_CONTRACT;
    }
}

app/src/AppBundle/Entity/Stamp.php
<?php

namespace AppBundle\Entity;

use AppBundle\Component\FileSettings;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\StampRepository")
 * @ORM\Table(name="stamps")
 */
class Stamp implements FileEntityInterface
{
    public const PAINTING_ID = 1;
    public const PAINTING_ID_PHY = 2;
    public const STAMP_ID    = 3;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime")
     * @ORM\Version
     * @var \DateTime
     */
    private $dateCreated;

    public function __construct()
    {
        $this->dateCreated = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     *
     * @return Stamp
     */
    public function setTitle(string $title): Stamp
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string $fileName
     *
     * @return Stamp
     */
    public function setFileName(string $fileName): FileEntityInterface
    {
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    /**
     * @param \DateTime $dateCreated
     *
     * @return Stamp
     */
    public function setDateCreated(\DateTime $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    /**
     * @return string
     */
    public function getImageSrc(): string
    {
        return DIRECTORY_SEPARATOR . FileSettings::STAMP_FOLDER . DIRECTORY_SEPARATOR . $this->fileName;
    }
}

app/src/AppBundle/Controller/ContractController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Component\Services\ContractFileService;
use AppBundle\Entity\Contract;
use AppBundle\Entity\FileEntityInterface;
use AppBundle\Entity\PhysicalPersonsLeaseAgreement;
use AppBundle\Repository\ContractRepository;
use AppBundle\Repository\DocumentRepository;
use AppBundle\Repository\StampRepository;
use AppBundle\Response\Json\ErrorJsonResponse;
use AppBundle\Response\Json\HtmlJsonResponse;
use AppBundle\Response\Json\SuccessJsonResponse;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use PhpOffice\PhpWord\Exception\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contracts", name="app_contracts_")
 */
class ContractController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     *
     * @param ContractFileService $fileService
     * @param DocumentRepository  $documentRepo
     * @param StampRepository     $stampRepo
     *
     * @return Response
     */
    public function main(
        ContractFileService $fileService,
        DocumentRepository $documentRepo,
        StampRepository $stampRepo
    ): Response {
        return $this->render('@App/Contracts/main.html.twig', [
            'contracts' => $fileService->getAllContracts(),
            'documents' => $documentRepo->findAll(),
            'stamps'    => $stampRepo->findAll(),
            'addresses' => $fileService->getAddressForCargo(),
        ]);
    }

    /**
     * @Route("/create_contract", name="create_contract")
     *
     * @param Request             $request
     * @param ContractFileService $contractFileService
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function createContract(Request $request, ContractFileService $contractFileService): Response
    {
        $response = new RedirectResponse($this->generateUrl('app_contracts_main'));

        try {
            $response = $this->file($contractFileService->createAndGiveContractFromRequest($request));
        } catch (\Throwable $exception) {
            $this->addFlash('error', $exception->getMessage());
        }

        return $response;
    }

    /**
     * @Route("/download/{key}/{id}", name="download")
     *
     * @param string                 $key
     * @param int                    $id
     * @param EntityManagerInterface $entityManager
     *
     * @return BinaryFileResponse
     */
    public function download(string $key, int $id, EntityManagerInterface $entityManager): BinaryFileResponse
    {
        /** @var FileEntityInterface $entity */
        $entity = $entityManager->getRepository(Contract::CLASSES[$key])->find($id);

        return $this->file($entity->getFileName());
    }

    /**
     * @Route("/remove/{key}/{id}", name="remove")
     *
     * @param string                 $key
     * @param int                    $id
     * @param EntityManagerInterface $entityManager
     *
     * @return JsonResponse
     */
    public function remove(string $key, int $id, EntityManagerInterface $entityManager): JsonResponse
    {
        try {
            /** @var FileEntityInterface $entity */
            $entity = $entityManager->getRepository(Contract::CLASSES[$key])->find($id);

            $entityManager->remove($entity);
            $entityManager->flush();

            return new SuccessJsonResponse('Контракт был удалён.');
        } catch (\Throwable $exception) {
            return  new ErrorJsonResponse($exception);
        }
    }
}

app/src/AppBundle/Resources/views/Contracts/main.html.twig
{% extends '@App/Default/base.html.twig' %}

{% set russianNames = constant('AppBundle\\Entity\\Document::RUSSIAN_TITLES') %}
{% set russianNamesForAddress = constant('AppBundle\\Entity\\CargoContract::TRANSLATE_FOR_ADRESS') %}

{% block body %}
    <h2 align="center">Контракты</h2>

    <div class="container">
        <div class="row">
            <button class=" btn btn-primary js-btn-add-contract">Добавить контракт</button>
            <div class="js-new-contract-container" style="display: none">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <form action="{{ path('app_contracts_create_contract') }}" method="post" class="form-contract-create">
                                <select name="documents" class="form-control select-docs">
                                    {% for document in documents %}
                                        <option value="{{ document.id }}"
                                                {{ loop.first ? 'selected' : '' }}
                                                data-array-values="{{ document.mergeFieldsWithoutNotUsedFields|json_encode }}"
                                        >{{ document.russinTitle }}</option>
                                    {% endfor %}
                                </select> <br>

                                <div class="fields"></div>
                                <input class="btn btn-primary" type="submit" value="Создать">
                            </form>
                        </div>
                        <div class="col-md-3">
                            <table class="table">
                                <thead>
                                <th>Имя росписи</th>
                                <th>Изображение</th>
                                </thead>
                                <tbody>
                                {% for stamp in stamps %}
                                    <tr>
                                        <td>{{ stamp.title }}</td>
                                        <td><img src="{{ stamp.imageSrc }}" width="100" height="100"></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 100px">
            {% for key, contracts in contracts %}
                <div class="">
                    <h3 class="btn btn-info btn-contracts">{{ russianNames[key] }}</h3>
                    <div style="display: none">
                        {{ include('@App/Contracts/table.html.twig', {"contracts": contracts, "key": key}) }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="js-data-for-cargo" style="display: none">
        <div class="form-group row">
            {% for name, address in addresses %}
            <label class="col-sm-5 col-form-label">{{russianNamesForAddress[name]}}</label>
            <div class="col-sm-7">
                <select class="form-control" name="{{name}}">
                    {% for name in address %}
                        <option value="{{ name }}">{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(() => {
            const $addNewStampBtn = $('.js-btn-add-contract');
            const $containerForForm = $('.js-new-contract-container');
            const $btnsForRemove = $('.js-remove-contract');
            const $select = $('.select-docs');
            const $fields = $('.fields');

            $('.btn-contracts').on('click', (event) => {
                $(event.currentTarget).next().toggle();
            });

            $btnsForRemove.on('click', (event) => {
                const $btn = $(event.currentTarget);
                const $tr = $btn.parent().parent();

                $.ajax($btn.data('url-for-remove'), {
                    beforeSend: () => {
                        $btn.attr('disabled', true);
                    },
                    success: (res) => {
                        if (res.status === 'success') {
                            $tr.remove();
                        } else {
                            alert(res.message);
                            $btn.attr('disabled', false);
                        }
                    },
                });
            });

            $addNewStampBtn.on('click', () => {
                $containerForForm.toggle();
            });

            $fields.html(getInputFields($select.children("option:selected").data('array-values')));

            $select.on('change', function () {
                const arrayValues = $(this).children("option:selected").data('array-values');

                let html = getInputFields(arrayValues);

                if (0 === html.length) {
                    html = 'Полей не найдено';
                }

                $fields.html(html);
                console.log($(this).val());
                // its CargoContract id
                // need customfields
                if ($(this).val() === '3') {
                    const block = $('.js-data-for-cargo');
                    const html = block.show().html();

                    $fields.append(html);

                    block.remove();
                }
            });

            function getInputFields(obj) {
                let html = '';

                if (null === obj) {
                    return '';
                }

                if (0 !== obj.length) {

                    for (let prop in obj) {
                        html += getInput(prop, obj[prop]);
                    }
                }

                return html;
            }

            function getInput(name, value) {
                return `
                    <div class="form-group row">
                        <label for="${value}" class="col-sm-5 col-form-label">${name}</label>
                        <div class="col-sm-7">
                          <input type="text" class="form-control" id="${value}" name="${value}" placeholder="${name}">
                        </div>
                    </div>
                `;
            }
        });
    </script>
{% endblock %}

app/src/AppBundle/Resources/views/Contracts/table.html.twig
<table class="table">
    <thead></thead>
    <tbody>
    {% if contracts %}
        {% for contract in contracts %}
            <tr>
                <td>{{ contract.id }}</td>
                <td>{{ contract.title }}</td>
                <td>{{ contract.dateCreated|date('d/m/Y h:i') }}</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="{{ path('app_contracts_download', {"id": contract.id, "key": key}) }}">Скачать</a>
                    <button class="btn btn-sm btn-primary js-remove-contract" data-url-for-remove="{{ path('app_contracts_remove', {"id": contract.id, "key": key}) }}">Удалить</button>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td>Нет записей</td>
        </tr>
    {% endif %}
    </tbody>
</table>